apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: agriculture-app
type: Opaque
data:
  # Base64 encoded values:
  # Echo -n "value" | base64
  SECRET_KEY: c3VwZXJzZWNyZXRrZXk= 
  GROQ_API_KEY: Z3NrX3I2cDQ3aWdiY0ZoUG9IRm1DMTBZV0dyeWIzRllkb0ZvYVhEUHViaG5xRGh1aWt0MHc4MlQ= 
